### ISSUE TITLE
Skips blinking at times

### ISSUE THREAD

**Issue by dhakadamit** [leonderijke/jQuery-Modern-Blink#9]
Check this link

http://mp-web.herokuapp.com/watchlists/template/bullion

I want every change to cause a blinking effect. It works beautifully most of the times but then some changes are skipped. Why does this happen?

**Comment by leonderijke** [comment]
I don't know without debugging your code. You should try to make a reduced test case, so you can reproduce your problem in an isolated environment.

Closing this for now. Feel free to reopen if you find an issue with Modern Blink itself.
